# Generated by Django 4.2.7 on 2025-07-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#0072CE', help_text='Cor em hexadecimal', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(default='fas fa-lightbulb', help_text='Classe do ícone FontAwesome', max_length=50, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Faltou')], default='enrolled', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Avaliação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#28a745', max_length=7, verbose_name='Cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Nível de Dificuldade',
                'verbose_name_plural': 'Níveis de Dificuldade',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('format', models.CharField(choices=[('workshop', 'Workshop'), ('minicurso', 'Minicurso'), ('palestra', 'Palestra'), ('hands_on', 'Hands-on')], default='workshop', max_length=20, verbose_name='Formato')),
                ('duration', models.CharField(help_text='Ex: 4h, 2 dias', max_length=50, verbose_name='Duração')),
                ('max_participants', models.PositiveIntegerField(default=30, verbose_name='Máximo de Participantes')),
                ('highlights', models.JSONField(default=list, help_text='Lista de tópicos principais', verbose_name='Destaques')),
                ('instructor_name', models.CharField(max_length=200, verbose_name='Nome do Instrutor')),
                ('instructor_bio', models.TextField(blank=True, verbose_name='Bio do Instrutor')),
                ('instructor_avatar', models.ImageField(blank=True, upload_to='instructors/', verbose_name='Avatar do Instrutor')),
                ('xp_reward', models.PositiveIntegerField(default=100, verbose_name='Recompensa XP')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Inscrição')),
                ('image', models.ImageField(blank=True, upload_to='workshops/', verbose_name='Imagem')),
                ('gradient_colors', models.CharField(default='from-blue-500 to-purple-500', help_text='Classes Tailwind para gradiente', max_length=100, verbose_name='Cores do Gradiente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.category', verbose_name='Categoria')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.level', verbose_name='Nível')),
                ('participants', models.ManyToManyField(blank=True, related_name='enrolled_workshops', through='workshops.Enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workshops.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'workshop')},
        ),
    ]
