# Generated by Django 4.2.7 on 2025-07-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(default='fas fa-award', max_length=50, verbose_name='Ícone')),
                ('color_gradient', models.CharField(default='from-blue-400 to-blue-600', max_length=100, verbose_name='Gradiente de Cor')),
                ('criteria_type', models.CharField(choices=[('workshops_completed', 'Workshops Concluídos'), ('streak_days', 'Dias Consecutivos'), ('total_xp', 'XP Total'), ('first_workshop', 'Primeiro Workshop'), ('level_reached', 'Nível Alcançado'), ('custom', 'Critério Personalizado')], max_length=20, verbose_name='Tipo de Critério')),
                ('criteria_value', models.PositiveIntegerField(help_text='Valor necessário para conquistar o badge', verbose_name='Valor do Critério')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_rare', models.BooleanField(default=False, verbose_name='Raro')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('target_value', models.PositiveIntegerField(verbose_name='Valor Alvo')),
                ('challenge_type', models.CharField(choices=[('workshops_week', 'Workshops na Semana'), ('streak_challenge', 'Desafio de Sequência'), ('xp_challenge', 'Desafio de XP')], max_length=50, verbose_name='Tipo')),
                ('xp_reward', models.PositiveIntegerField(default=100, verbose_name='Recompensa XP')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('min_xp', models.PositiveIntegerField(verbose_name='XP Mínimo')),
                ('color_gradient', models.CharField(default='from-gray-400 to-gray-600', max_length=100, verbose_name='Gradiente de Cor')),
                ('icon', models.CharField(default='fas fa-user', max_length=50, verbose_name='Ícone')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['min_xp'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conquistado em')),
            ],
            options={
                'verbose_name': 'Badge do Usuário',
                'verbose_name_plural': 'Badges dos Usuários',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.PositiveIntegerField(default=0, verbose_name='Progresso Atual')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.challenge')),
            ],
            options={
                'verbose_name': 'Desafio do Usuário',
                'verbose_name_plural': 'Desafios dos Usuários',
            },
        ),
    ]
