# Generated by Django 4.2.7 on 2025-07-20 02:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='color_gradient',
        ),
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Cor em formato hexadecimal (ex: #FF0000)', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='level',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição motivacional do nível', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.CharField(default='fas fa-star', help_text='Classe do ícone FontAwesome (ex: fas fa-star)', max_length=100, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='level',
            name='min_xp',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP Mínimo'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
