# Generated by Django 4.2.7 on 2025-07-20 02:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0003_remove_level_color_gradient_level_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='color_gradient',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='is_rare',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='order',
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#10B981', help_text='Cor em formato hexadecimal', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('first_workshop', 'Primeiro Workshop'), ('workshops_completed', 'Workshops Concluídos'), ('streak_days', 'Dias Consecutivos'), ('xp_accumulated', 'XP Acumulado'), ('level_reached', 'Nível Alcançado')], max_length=50, verbose_name='Tipo de Critério'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor do Critério'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='fas fa-medal', help_text='Classe do ícone FontAwesome', max_length=100, verbose_name='Ícone'),
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop', verbose_name='Workshop')),
            ],
            options={
                'verbose_name': 'Transação de XP',
                'verbose_name_plural': 'Transações de XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, verbose_name='XP Total')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Dias Consecutivos')),
                ('last_activity', models.DateField(blank=True, null=True, verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.level', verbose_name='Nível Atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
