# Generated by Django 4.2.7 on 2025-07-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_badge_options_remove_badge_color_gradient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xptransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='workshop',
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='color',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='color',
        ),
        migrations.RemoveField(
            model_name='level',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='badge',
            name='color_gradient',
            field=models.CharField(default='from-blue-400 to-blue-600', max_length=100, verbose_name='Gradiente de Cor'),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Raro'),
        ),
        migrations.AddField(
            model_name='badge',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='level',
            name='color_gradient',
            field=models.CharField(default='from-gray-400 to-gray-600', max_length=100, verbose_name='Gradiente de Cor'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('workshops_completed', 'Workshops Concluídos'), ('streak_days', 'Dias Consecutivos'), ('total_xp', 'XP Total'), ('first_workshop', 'Primeiro Workshop'), ('level_reached', 'Nível Alcançado'), ('custom', 'Critério Personalizado')], max_length=20, verbose_name='Tipo de Critério'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_value',
            field=models.PositiveIntegerField(help_text='Valor necessário para conquistar o badge', verbose_name='Valor do Critério'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='fas fa-award', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.CharField(default='fas fa-user', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='level',
            name='min_xp',
            field=models.PositiveIntegerField(verbose_name='XP Mínimo'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='XPTransaction',
        ),
    ]
